### ISSUE TITLE
Pycdg displaySize

### ISSUE THREAD

**Issue by deckarep** [kelvinlawson/pykaraoke#19]
Hi Kelvin,

Is there a way to set the displaySize when importing the pycdg module directly?

I want to be able to set the set the size to larger than 640*480 but can't figure out how to make that work.

Also is there a way to toggle full screen?

This module is very awesome and I'm trying to avoid having to customize the code.  If I need to I can as well and perhaps contribute a patch.

**Comment by kelvinlawson** [comment]
I don't think there is a way to do this from an import, but I'd welcome a patch.
